### ISSUE TITLE
Add username as an available field

### ISSUE THREAD

**Issue by mackensen** [LafColITS/moodle-report_roster#1]
This has been discussed on the [Moodle Plugins Directory](https://moodle.org/plugins/view.php?plugin=report_roster) so I'm bringing the discussion here. The request is to display the username in addition to the fullname. This requires two changes:
- The user_picture() function call needs the username passed as an extra field.
- The username has to be outputted in a second span.

I'm going to push some code up as an example but to make it into a release this behavior would need to be controlled somehow.

**Comment by azito122** [comment]
This has been implemented.
