### ISSUE TITLE
Option to display in Boost flat navigation

### ISSUE THREAD

**Issue by azito122** [LafColITS/moodle-report_roster#15]
In the new Boost navigation, course reports are much harder to get to. We'd like Roster to be more easily available, so we're going to add an option that will cause it to appear in the flat nav (left drawer) menu.

**Comment by azito122** [comment]
@mackensen Two questions:
1. Where should the link be positioned? I've got it directly under Participants right now.
2. What icon should be used?

**Comment by mackensen** [comment]
@azito122 Under Participants makes sense, and is in line with previous suggestions. For the second, `fa-clipboard` seems close.

**Comment by azito122** [comment]
I've added options for the display name (for flat navigation link), and position in the flat navigation. In response to concerns expressed outside of this thread:

> Is "Flat nav" as opposed to "Flat (N|n)avigation used publicly elsewhere in Moodle?
No idea. I changed it to use "flat navigation" consistently.

> Are you planning on tests for the flatnav changes?
Added behat test.
