### ISSUE TITLE
Report only displays last specified profile field

### ISSUE THREAD

**Issue by upats** [LafColITS/moodle-report_roster#32]
Hi, first, thanks so much for adding the ability to add more profile fields to the already awesome Roster report! In my initial tests I am only able to get one profile field (whichever is listed last in the newline list) to show up. I sincerely hope I am not missing something obvious....

I have tried this on a Moodle 3.6 and a Moodle 3.8 site.

Here is how my fields list is set up
![2020-01-14_16-08-05](https://user-images.githubusercontent.com/7084108/72394703-00185d80-36ec-11ea-82e2-dfffa1e12ec7.png)

And here is the result I get:
![2020-01-14_16-07-59](https://user-images.githubusercontent.com/7084108/72394743-24743a00-36ec-11ea-8c03-1573e629296a.png)

If I leave single field, or swap the order, I get whatever is listed last to successfully display.

**Comment by azito122** [comment]
Thank you for the prompt report! This is fixed in #33, which we will try to merge and release ASAP.
