### ISSUE TITLE
Support for timezone display

### ISSUE THREAD

**Issue by aruethe2** [LafColITS/moodle-report_roster#34]
I tried to add "timezone" to the list of fields displayed on the roster report, but it didn't work.  Is it possible to add timezone to the supported fields?  Or should I be using a different term?

**Comment by azito122** [comment]
This has to do with the profile fields Moodle loads by default. I've added PR #35, which will ensure that `timezone` is available. It also adds the `currenttime` special value (see PR for more info).

**Comment by aruethe2** [comment]
Great -- thank you.  Does PR #35 also allow the description profile field to be used (#29) is that a different issue?

**Comment by azito122** [comment]
No, this is unrelated to #29.

**Comment by mackensen** [comment]
This was included in v3.6.3.
