### ISSUE TITLE
Print not working in French

### ISSUE THREAD

**Issue by monicangela** [LafColITS/moodle-report_roster#40]
Hello,
We are using the v3.6.3 2020072200 version of the plugin and the print option is not working when the site is in French. When I change to English everything works. I just can't ask teacher to switch between languages to be able to print the roster.

Could it be possible to see where this comes from ? 

Thanks,
Monica

**Comment by mackensen** [comment]
Hi @monicangela, that's certainly unexpected. I'll try to reproduce the error, but if you could include a screenshot showing that error that would be helpful.

**Comment by monicangela** [comment]
Hi,

It actually started working after I changed the language to English a few times. Before that nothing happened when I clicked on the "Imprimable" button.
I guess everything is fine now.
Thanks
