### ISSUE TITLE
Roster - Error - Unknown column 'u.fullname' in 'field list'

### ISSUE THREAD

**Issue by acquaalta** [LafColITS/moodle-report_roster#45]
Hi,
Moodle version: 4.3.3
Plugin version: v4.0.1 (2022041200)

After installing the "Roster" plugin, when trying to access the "Roster" report, the following exception message is shown on the screen:

```
Error reading from database

Debug info: Unknown column 'u.fullname' in 'field list'
SELECT u.id,u.picture,u.firstname,u.lastname,u.firstnamephonetic,u.lastnamephonetic,u.middlename,u.alternatename,u.imagealt,u.email,u.username,u.timezone,u.fullname
FROM mdl_user u
JOIN (SELECT DISTINCT eu1_u.id
FROM mdl_user eu1_u
JOIN mdl_user_enrolments ej1_ue ON ej1_ue.userid = eu1_u.id
JOIN mdl_enrol ej1_e ON (ej1_e.id = ej1_ue.enrolid AND ej1_e.courseid = ?)
WHERE 1 = 1 AND eu1_u.deleted = 0) je ON je.id = u.id
WHERE u.deleted = 0 ORDER BY u.lastname, u.firstname, u.id
[array (
0 => '3',
)]
Error code: dmlreadexception×Dismiss this notification

Stack trace:
line 494 of /lib/dml/moodle_database.php: dml_read_exception thrown
line 293 of /lib/dml/moodle_read_slave_trait.php: call to moodle_database->query_end()
line 1398 of /lib/dml/mysqli_native_moodle_database.php: call to mysqli_native_moodle_database->query_end()
line 1683 of /lib/enrollib.php: call to mysqli_native_moodle_database->get_records_sql()
line 64 of /report/roster/index.php: call to get_enrolled_users()
```

I bypassed this error by changing the "report_roster | fields" setting value from the original one (which includes "fullname") to:
firstname
lastname

And it works, because the u.firstname and u.lastname fields exist in the Moodle database. Clearly, as can be seen in my situation, some Moodle systems don't have the "fullname" field in their "user" table. Can the plugin be updated to it will take care of such situations?

Thanks :-)

**Comment by mackensen** [comment]
@acquaalta what I mean is that while fullname is the standard setting for the plugin, there isn't such a column in the user table. It's a convenience to the user, and fields that aren't on the `$USER` object are stripped out when the database query gets built (from `report_roster_profile_fields_query()' in `locallib.php`):

``` php
    foreach ($fieldsconfig as $field) {
        $field = trim($field);

        if ( property_exists($USER, $field)) {
            $extrafields[] = $field;
        }
    }
```

**Comment by mackensen** [comment]
@acquaalta I've released `v4.1.0` which addresses this issue. Thanks for the report.

**Comment by acquaalta** [comment]
Hi @mackensen,
Thanks a lot for fixing the issue so fast :-)

**Comment by Richardvi** [comment]
Does it have to do with this?
![image](https://github.com/LafColITS/moodle-report_roster/assets/5486910/afd1fa88-5d09-4e11-abf3-96d1cd86fc85)

**Comment by mackensen** [comment]
@Richardvi what happened is that I included the wrong field in the original fix. `v4.1.1` addresses this. Roster still supports setting `fullname` in the configuration and that field is constructed from other values.
