### ISSUE TITLE
[4.3.3] Unknown column 'u.fullname' in 'field list'

### ISSUE THREAD

**Issue by Richardvi** [LafColITS/moodle-report_roster#49]
I installed the plugin as default, but when trying to access the report from a course I get the following error:

Debug info: Unknown column 'u.fullname' in 'field list'
SELECT u.id,u.picture,u.firstname,u.lastname,u.firstnamephonetic,u.lastnamephonetic,u.middlename,u.alternatename,u.imagealt,u.email,u.username,u.timezone,u.fullname
FROM mdl_user u
JOIN (SELECT DISTINCT eu1_u.id
FROM mdl_user eu1_u
JOIN mdl_user_enrolments ej1_ue ON ej1_ue.userid = eu1_u.id
JOIN mdl_enrol ej1_e ON (ej1_e.id = ej1_ue.enrolid AND ej1_e.courseid = ?)
WHERE 1 = 1 AND eu1_u.deleted = 0) je ON je.id = u.id
WHERE u.deleted = 0 ORDER BY u.lastname, u.firstname, u.id
[array (
0 => '22771',
)]
Error code: dmlreadexception

Where does fullname come from? It seems I don't have that in my mdl_user

**Comment by mackensen** [comment]
@Richardvi this sounds like the issue reported in #45. What version of the plugin do you have?

**Comment by Richardvi** [comment]
I just downloaded the latest version. Is this a regression? Filename is report_roster_moodle44_2024050100

**Comment by mackensen** [comment]
This should be fixed (for real this time) in `v4.1.1`.
