### ISSUE TITLE
[4.3.3] Can't access manage templates

### ISSUE THREAD

**Issue by Richardvi** [LafColITS/moodle-report_roster#50]
When trying to access 'manage templates' I'm getting this error:

Manage Templates
Coding error detected, it must be fixed by a programmer: get_all_user_name_fields() is deprecated. Please use the \core_user\fields API instead

More information about this error

**Comment by mackensen** [comment]
@Richardvi that doesn't sound like an error from the Roster report. It doesn't have functionality by that name and doesn't invoke `get_all_user_name_fields`.

**Comment by Richardvi** [comment]
Yes, apologies. I posted that wrong. It's the shortmath question creating this error...
